name: "asl_classifier"
platform: "tensorrt_plan"
max_batch_size: 0
input  [ { name: "input",  data_type: TYPE_FP32, dims: [63] } ]
output [ { name: "output", data_type: TYPE_FP32, dims: [26] } ]
dynamic_batching { }
instance_group [ { count: 1, kind: KIND_GPU } ]
