services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.03-py3
    runtime: nvidia
    ports:
      - "8010:8000"
      - "8011:8001"
      - "8012:8002"
    volumes:
      - ./triton_repo:/models
    command: tritonserver --model-repository=/models --model-control-mode=poll --exit-on-error=false

  tutor-app:
    build: .
    image: sign-tutor:latest
    runtime: nvidia
    ports:
      - "7860:7860"
    volumes:
      - ./languages:/app/languages
      - ./src:/app/src
      - ./datasets:/app/datasets
      - ./training:/app/training
    depends_on:
      - triton
