name: "bsl_classifier"
platform: "onnxruntime_onnx"
max_batch_size: 64
input  [ { name: "input",  data_type: TYPE_FP32, dims: [126] } ]
output [ { name: "output", data_type: TYPE_FP32, dims: [26] } ]
instance_group [ { count: 1, kind: KIND_GPU } ]
